### PR TITLE
Fix postal address

### LINKED ISSUE #133: Fix address
It should be the postal address, not the space address.

### PR DESCRIPTION
**Pull request by dbrgn**
We should list the postal address, not the location of the space.

Fixes #133.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -43,7 +43,7 @@ fn main() {
         .logo("https://www.coredump.ch/wp-content/uploads/2016/11/logo.png")
         .url("https://www.coredump.ch/")
         .location(api::Location {
-            address: Some("Holzwiesstrasse 50, 8645 Jona, Switzerland".into()),
+            address: Some("Neue Jonastrasse 107, 8640 Rapperswil, Switzerland".into()),
```
Comment (rnestler) [inline src/main.rs:46]: Actually I'm not sure if most spaces implement it that way :wink: Maybe we should make it clearer in the specs by having a `postal_address` and a `address` field.

Comment (dbrgn) [reply src/main.rs:46]: Changing semantics of `address` would not be reverse compatible :slightly_smiling_face: Also, regarding the address I agree that the coordinates are more useful in order to find the space.

The postal address is important to know if you want to send a letter or some other stuff to another hackerspace.

Anyways, this discussion should belong in the schema repo, not here.
